#!/usr/bin/env python3
"""
Regenerate resources/bombertalk_gfx.r (and the low-memory variant) from the
.pict files in resources/gfx/.

Retro68's Rez does not implement the Apple Rez `read 'TYPE' (id) "file";`
directive, so PICT binaries have to be embedded inline as `data` blocks with
hex literals. This script does that conversion.

What gets embedded, at which resource id, and whether it survives into the
low-memory build all come from resources/gfx/assets.json -- the same manifest
tools/build-asset.sh builds against. Add an asset there, not here.

PICT files carry a 512-byte file header that GetPicture() does not expect
inside a resource fork; it is stripped here.

Run after regenerating PICTs (tools/build-asset.sh does this for you):
    python3 scripts/embed-gfx.py
"""
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GFX_DIR = os.path.join(REPO_ROOT, 'resources', 'gfx')
MANIFEST = os.path.join(GFX_DIR, 'assets.json')
OUT_FILE_FULL = os.path.join(REPO_ROOT, 'resources', 'bombertalk_gfx.r')
OUT_FILE_LOWMEM = os.path.join(REPO_ROOT, 'resources', 'bombertalk_gfx_lowmem.r')

# Tiers that produce resource-fork PICTs, in embedding order. 'sdl' is a BMP
# atlas for the modern client and never enters a resource fork.
RESOURCE_TIERS = ('color', 'se')

HEADER = '''/*
 * {fname} -- Graphics resources{suffix}.
 *
 * AUTO-GENERATED by scripts/embed-gfx.py from the .pict files in
 * resources/gfx/, driven by resources/gfx/assets.json. Do not edit by hand;
 * regenerate after asset changes (tools/build-asset.sh does it for you).
 *
 * Retro68 Rez does not support `read 'PICT' (id) "path";` so PICT bytes
 * are embedded inline as hex `data` blocks. The 512-byte file header
 * that the PICT writer emits is stripped -- resource-fork PICTs start
 * with the picture body opcodes directly.
 *
{body} */
'''


def pict_filename(asset_name, tier, frames, index):
    """resources/gfx naming: <name>_<tier>.pict, or _f<N> when animated."""
    if frames == 1:
        return f'{asset_name}_{tier}.pict'
    return f'{asset_name}_{tier}_f{index}.pict'


def load_resources():
    """Flatten assets.json into embedding order: [(id, label, file, lowmem)]."""
    try:
        with open(MANIFEST) as f:
            manifest = json.load(f)
    except FileNotFoundError:
        sys.exit(f'error: missing manifest {MANIFEST}')
    except json.JSONDecodeError as exc:
        sys.exit(f'error: {MANIFEST} is not valid JSON: {exc}')

    resources = []
    seen_ids = {}
    for asset in manifest.get('assets', []):
        name = asset['name']
        frames = int(asset.get('frames', 1))
        for tier in RESOURCE_TIERS:
            spec = asset.get('tiers', {}).get(tier)
            if spec is None:
                continue
            ids = spec['ids']
            if len(ids) != frames:
                sys.exit(f'error: {name}.{tier} lists {len(ids)} ids for '
                         f'{frames} frame(s)')
            for index, res_id in enumerate(ids):
                if res_id in seen_ids:
                    sys.exit(f'error: resource id {res_id} used by both '
                             f'{seen_ids[res_id]} and {name}.{tier}')
                seen_ids[res_id] = f'{name}.{tier}'
                resources.append((
                    res_id,
                    spec['label'].format(n=index),
                    pict_filename(name, tier, frames, index),
                    bool(spec.get('lowmem', False)),
                ))
    return resources


def human(size):
    return f'{size / 1024:.1f} KB' if size >= 1024 else f'{size} B'


def describe(resources):
    """The comment block listing what a variant embeds."""
    lines = [' * Resources embedded:']
    for res_id, label, fname, _ in resources:
        path = os.path.join(GFX_DIR, fname)
        size = human(os.path.getsize(path)) if os.path.isfile(path) else '?'
        lines.append(f' *   {res_id:<4} {label:<16} {fname} ({size})')
    return '\n'.join(lines) + '\n'


def emit(path, resources, variant_suffix):
    lines = [HEADER.format(
        fname=os.path.basename(path),
        suffix=variant_suffix,
        body=describe(resources),
    )]
    for res_id, label, fname, _ in resources:
        src = os.path.join(GFX_DIR, fname)
        if not os.path.isfile(src):
            sys.exit(f'error: missing {src} (declared in assets.json)')
        with open(src, 'rb') as f:
            data = f.read()
        if len(data) > 512 and data[:512] == b'\x00' * 512:
            data = data[512:]
        hex_str = data.hex().upper()
        lines.append(f'data \'PICT\' ({res_id}, "{label}") {{')
        for i in range(0, len(hex_str), 32):
            chunk = hex_str[i:i + 32]
            grouped = ' '.join(chunk[j:j + 4] for j in range(0, len(chunk), 4))
            lines.append(f'    $"{grouped}"')
        lines.append('};')
        lines.append('')
    with open(path, 'w') as f:
        f.write('\n'.join(lines))
    total = sum(os.path.getsize(os.path.join(GFX_DIR, r[2])) for r in resources)
    print(f'wrote {os.path.relpath(path, REPO_ROOT)} '
          f'({len(resources)} PICTs, {human(total)} of picture data)')


def main():
    if not os.path.isdir(GFX_DIR):
        sys.exit(f'error: {GFX_DIR} does not exist')

    resources = load_resources()
    if not resources:
        sys.exit('error: assets.json declares no resource-fork PICTs')

    emit(OUT_FILE_FULL, resources, '')
    emit(OUT_FILE_LOWMEM, [r for r in resources if r[3]], ' (low-memory build)')


if __name__ == '__main__':
    main()
