#!/usr/bin/env python3
"""
Regenerate resources/bombertalk_gfx.r from the .pict files in resources/gfx/.

Retro68's Rez does not implement the Apple Rez `read 'TYPE' (id) "file";`
directive, so the PICT binary has to be embedded inline as a `data` block
with hex literals. This script does that conversion.

PICT 2.0 files produced by pixelcraft's grid2pict have a 512-byte file
header that Mac's GetPicture() does not expect inside a resource fork --
the first 512 bytes are stripped here.

Run after regenerating bomb PICTs from pixelcraft:
    python3 scripts/embed-gfx.py
"""
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GFX_DIR = os.path.join(REPO_ROOT, 'resources', 'gfx')
OUT_FILE = os.path.join(REPO_ROOT, 'resources', 'bombertalk_gfx.r')

# (resource_id, resource_name, filename_in_gfx_dir)
FRAMES = [
    (140, 'Bomb f0', 'bomb_color_f0.pict'),
    (141, 'Bomb f1', 'bomb_color_f1.pict'),
    (142, 'Bomb f2', 'bomb_color_f2.pict'),
]

HEADER = '''/*
 * bombertalk_gfx.r -- Bomb animation PICTs (color Macs, 32x32, 16 colors).
 *
 * AUTO-GENERATED by scripts/embed-gfx.py from the .pict files in
 * resources/gfx/. Do not edit by hand; regenerate after asset changes.
 *
 * Retro68 Rez does not support `read 'PICT' (id) "path";` so PICT bytes
 * are embedded inline as hex `data` blocks. The 512-byte file header
 * that grid2pict writes is stripped -- resource-fork PICTs start with
 * the picture body opcodes directly.
 *
 * Mac SE uses the PaintOval fallback path, no 1-bit PICTs required.
 */
'''

def main():
    if not os.path.isdir(GFX_DIR):
        print(f'error: {GFX_DIR} does not exist', file=sys.stderr)
        sys.exit(1)

    lines = [HEADER]
    for pid, name, fname in FRAMES:
        path = os.path.join(GFX_DIR, fname)
        if not os.path.isfile(path):
            print(f'error: missing {path}', file=sys.stderr)
            sys.exit(1)
        with open(path, 'rb') as f:
            data = f.read()
        if len(data) > 512:
            data = data[512:]
        hex_str = data.hex().upper()
        body = []
        for i in range(0, len(hex_str), 32):
            chunk = hex_str[i:i + 32]
            grouped = ' '.join(chunk[j:j + 4] for j in range(0, len(chunk), 4))
            body.append(f'    $"{grouped}"')
        lines.append(f'data \'PICT\' ({pid}, "{name}") {{')
        lines.extend(body)
        lines.append('};')
        lines.append('')

    with open(OUT_FILE, 'w') as f:
        f.write('\n'.join(lines))
    print(f'wrote {OUT_FILE} ({len(FRAMES)} PICTs embedded)')

if __name__ == '__main__':
    main()
