#!/usr/bin/env python3
"""
Regenerate resources/bombertalk_gfx.r from the .pict files in resources/gfx/.

Retro68's Rez does not implement the Apple Rez `read 'TYPE' (id) "file";`
directive, so the PICT binary has to be embedded inline as a `data` block
with hex literals. This script does that conversion.

PICT 2.0 files produced by pixelcraft's grid2pict have a 512-byte file
header that Mac's GetPicture() does not expect inside a resource fork --
the first 512 bytes are stripped here.

Run after regenerating bomb PICTs from pixelcraft:
    python3 scripts/embed-gfx.py
"""
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GFX_DIR = os.path.join(REPO_ROOT, 'resources', 'gfx')
OUT_FILE_FULL   = os.path.join(REPO_ROOT, 'resources', 'bombertalk_gfx.r')
OUT_FILE_LOWMEM = os.path.join(REPO_ROOT, 'resources', 'bombertalk_gfx_lowmem.r')

# (resource_id, resource_name, filename_in_gfx_dir)
FRAMES = [
    (140, 'Bomb f0',      'bomb_color_f0.pict'),
    (141, 'Bomb f1',      'bomb_color_f1.pict'),
    (142, 'Bomb f2',      'bomb_color_f2.pict'),
    (145, 'Bomb SE f0',   'bomb_se_f0.pict'),
    (146, 'Bomb SE f1',   'bomb_se_f1.pict'),
    (147, 'Bomb SE f2',   'bomb_se_f2.pict'),
    (150, 'Splash Color', 'splash_color.pict'),
    (250, 'Splash SE',    'splash_se.pict'),
]

# Resource IDs excluded from the low-memory build (Mac SE, 68k MacTCP).
# 140-142 = colour bomb frames (only rendered on colour Macs).
# 150 = colour splash (178 KB) is useless on a 1-bit Mac.
# SE bomb frames (145-147) and SE splash (250) stay -- they're what
# the SE build actually needs, and together they're ~22 KB.
LOWMEM_EXCLUDES = {140, 141, 142, 150}

HEADER = '''/*
 * {fname} -- Graphics resources{suffix}.
 *
 * AUTO-GENERATED by scripts/embed-gfx.py from the .pict files in
 * resources/gfx/. Do not edit by hand; regenerate after asset changes.
 *
 * Retro68 Rez does not support `read 'PICT' (id) "path";` so PICT bytes
 * are embedded inline as hex `data` blocks. The 512-byte file header
 * that pixelcraft writes is stripped -- resource-fork PICTs start with
 * the picture body opcodes directly.
 *
 * {body}
 */
'''

def emit(path, frames, variant_suffix, body_note):
    lines = [HEADER.format(
        fname=os.path.basename(path),
        suffix=variant_suffix,
        body=body_note,
    )]
    for pid, name, fname in frames:
        src = os.path.join(GFX_DIR, fname)
        if not os.path.isfile(src):
            print(f'error: missing {src}', file=sys.stderr)
            sys.exit(1)
        with open(src, 'rb') as f:
            data = f.read()
        if len(data) > 512:
            data = data[512:]
        hex_str = data.hex().upper()
        chunk_lines = []
        for i in range(0, len(hex_str), 32):
            chunk = hex_str[i:i + 32]
            grouped = ' '.join(chunk[j:j + 4] for j in range(0, len(chunk), 4))
            chunk_lines.append(f'    $"{grouped}"')
        lines.append(f'data \'PICT\' ({pid}, "{name}") {{')
        lines.extend(chunk_lines)
        lines.append('};')
        lines.append('')
    with open(path, 'w') as f:
        f.write('\n'.join(lines))
    print(f'wrote {path} ({len(frames)} PICTs)')

def main():
    if not os.path.isdir(GFX_DIR):
        print(f'error: {GFX_DIR} does not exist', file=sys.stderr)
        sys.exit(1)

    emit(
        OUT_FILE_FULL,
        FRAMES,
        '',
        'Resources embedded:\n *   140-142  bomb animation frames (32x32, 16 colours)\n *   150      splash screen for colour Macs (480x416, 8-bit)\n *   250      splash screen for Mac SE (240x208, 1-bit)',
    )

    lowmem_frames = [f for f in FRAMES if f[0] not in LOWMEM_EXCLUDES]
    emit(
        OUT_FILE_LOWMEM,
        lowmem_frames,
        ' (low-memory build)',
        'Low-memory variant: colour splash PICT 150 excluded to save\n * ~178 KB in the resource fork on the 68k MacTCP (Mac SE) target.',
    )

if __name__ == '__main__':
    main()
